# Generated by Django 3.0.4 on 2020-07-16 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pet',
            new_name='account',
        ),
    ]
