# Generated by Django 3.0.7 on 2020-08-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_is_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_saved',
        ),
    ]
