# Generated by Django 3.0.7 on 2020-07-17 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200716_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
