# Generated by Django 3.0.4 on 2020-07-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_auto_20200723_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, default='default_pet_img.jpg', upload_to='images/'),
        ),
    ]
