# Generated by Django 3.0.7 on 2020-07-17 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 7, 17), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
