# Generated by Django 3.0.4 on 2020-07-23 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200722_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2020, 7, 23), help_text='Please use the following format: <em>YYYY-MM-DD</em>.'),
        ),
    ]
