# Generated by Django 3.0.7 on 2020-08-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follower',
            new_name='followers',
        ),
    ]
